version: '3.4'

services:
  whanode:
    image: whanode
    networks:
      apinetwork:
        ipv4_address: 172.22.1.8
    ports:
      - "4444:3333"
    build:
      context: .
      args:
        MODE: production
      dockerfile: ./Dockerfile
    restart: always

networks:
  apinetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16